food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('items/', views.items, name='items'),
    path('details/<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('add/', views.AddNewItem.as_view(), name='add_items'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register, name='register'),
    path('login/', user_views.login_view,name='login_view'),
    path('logout/',user_views.logout_view, name='logout_view'),
    path('profile/', user_views.profilePage, name='profile')
]

urlpatterns += [

] +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Items(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete= models.CASCADE, default = 1)
    item_name = models.CharField(max_length = 200)
    item_desc = models.CharField(max_length = 200)
    item_price = models.IntegerField()
    item_image = models.URLField(max_length=2000, default='https://images4.alphacoders.com/132/1325361.png')

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(default='profilepic.jpj', upload_to = 'profile_pictures')
    location = models.CharField(max_length = 500)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import  Items

class ItemForm(forms.ModelForm):
    class Meta:
        model = Items
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Items
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

app_name = 'food'
# def index(request):
#     item_list = Items.objects.all()
#     context = {
#         'item_list': item_list
#     }
#     return render(request, 'food/index.html', context)

class IndexClassView(ListView):
    model = Items;
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def items(request):
    return HttpResponse("This is the item page")

# def detail(request, item_id):
#     item = Items.objects.get(pk = item_id)
#     context = {
#         'item': item
#     }
#     return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model= Items
    template_name = 'food/detail.html'

# def add_items(request):
#     form = ItemForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
    
#     return render(request, 'food/item_form.html', {'form': form})

class AddNewItem(CreateView):
    model = Items
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item_form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request, id):
    item = Items.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item_form.html', {'form': form, 'item': item})

def delete_item(request, id):
    item = Items.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item_delete.html',{'item':item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'welsome{username}')
            return redirect('login_view')
    else:
        form = RegisterForm()
    return render (request, 'users/register.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('food:index')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid form submission. Please check the form.')
    else:
        form = AuthenticationForm()

    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('food:index')

@login_required
def profilePage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Food App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse  justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'food:add_items' %}">Add item</a>
              <a class="nav-link active" href="#">Delete item</a>
              <a class="nav-link active" href="#">View item</a>
              {% if user.is_authenticated %}
                <a class="nav-link active" href="{% url 'logout_view' %}">Logout</a>
                <a class="nav-link active" href="{% url 'profile' %}">Profile</a>
              {% else %}
                <a class="nav-link active" href="{% url 'login_view' %}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
    </nav>

    {% if messages %}
      {% for message in messages %}

        <div class="alert alert-{{ message.tags }}">{{message}}</div>
        
      {% endfor %}
    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    {% block body %}
    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="{{object.item_image}}" alt="image" class="card" height="250px" width="250px">
            </div>
            <div class="col-md-6">
                <h1> {{ object.item_name }} </h1>
                <h2> {{ object.item_desc }} </h2>
                <h1> {{ object.item_price }} </h1>
                <a href="{% url 'food:delete_item' object.id %}">Delete</a>
            </div>
        </div>
    </div>

    
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block body %}

        {% for i in item_list %}

            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img src="{{i.item_image}}" alt="image" class="card" height="150px" width="150px">
                </div>
                <div class="col-md-4">
                    <h3>{{i.item_name}}</h3>
                    <h5>{{i.item_desc}}</h5>
                    <h6> {{i.item_price}} </h6>
                    <h6>{{i.user_name}}</h6>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:detail' i.id %}" class="btn btn-success">Details</a>
                </div>
            </div>

        {% endfor %}

    {% endblock %}

</body>
</html>

food/templates/food/item_delete.html
{% extends 'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete the item {{item.item_name}} </h2>
    <button type="submit">Confirm</button>
</form>

{% endblock %}

food/templates/food/item_form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-black">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}:
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}






<!-- 
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form> -->

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-black">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

<!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form> -->

users/templates/users/profile.html
<h1> {{ user.username }} </h1>
<img src="{{ user.profile.image.url }}" height="300px" width="400px">

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-black">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit">Sign-Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

<!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign-Up</button>
</form> -->